// auto generated by go tool dist

package main

const defaultCC = `mipsel-openwrt-linux-uclibc-gcc`
const defaultCXX = `mipsel-openwrt-linux-uclibc-g++`
const defaultPkgConfig = `/usr/bin/pkg-config`
