// Code generated by go tool dist; DO NOT EDIT.

package cfg

const DefaultPkgConfig = `/usr/bin/pkg-config`
func DefaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "gcc"
	}
	return "mipsel-openwrt-linux-uclibc-gcc"
}
func DefaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "g++"
	}
	return "mipsel-openwrt-linux-uclibc-g++"
}
