// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `/usr/bin/pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "gcc"
	}
	return "mipsel-openwrt-linux-uclibc-gcc"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "g++"
	}
	return "mipsel-openwrt-linux-uclibc-g++"
}
