// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `/home/lintel/PandoraBox-MT7621/staging_dir/host/bin/pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "gcc"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "g++"
}
